### ISSUE TITLE
Determine messaging strategy

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#1]
## Description
Research how to facilitate messaging in a distributed system. In particular:
* How to frequently receive all messages sent to a user
* How to notify all recipients when message is sent 

Some tools include:
* Web sockets

## Tasks
- [x] Quick diagram of how messaging will work
- [x] Follow websocket messaging tutorial carefully
- [ ] List of -ilities, considerations for sockets and messaging
- [x] Try Web Sockets for basic POC
- [ ] Try Socket.io for basic POC

## Acceptance Criteria
- [ ] List of considerations for messaging architecture
- [ ] List of options considered, with pros and cons
- [ ] Selection option, with rationale
- [ ] Proof-of-concept with selected option

**Comment by skitterm** [comment]
![diagram](https://user-images.githubusercontent.com/5875149/75412323-f2ebb280-58d6-11ea-901b-349bbac8b726.jpg)

**Comment by skitterm** [comment]
[messaging-flow.pdf](https://github.com/skitterm/message-app/files/4291031/messaging-flow.pdf)

**Comment by skitterm** [comment]
![messagingFlow](https://user-images.githubusercontent.com/5875149/76136853-f70c8400-5fea-11ea-8920-79ca195b8dc0.png)
