### ISSUE TITLE
Send messages

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#10]
## Description
_As a user, I need to send messages to other members and channels._

## Tasks
- [x] Create a text box on rooms user is a part of
- [x] Create "send" button, enabled or disabled
- [x] When hitting "send", send web socket message
- [x] When hitting "send", store message in DB

## Acceptance criteria
- [ ] On rooms I have sent messages, I can enter message text in a text box
- [ ] "Send" button enables, disables as field has content, is empty
- [ ] Upon pressing "send", the message is sent to other members in the room
- [ ] All sent messages are visible on the room thread after refreshing
