### ISSUE TITLE
Receive messages

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#11]
## Description
_As a user, I need to be able to receive messages sent directly to me by a member, or sent to a channel that I am part of._

## Tasks
- [x] Set up web socket to receive communication
- [x] Display received messages to the screen in real-time
- [x] Show a notification on the room when a message from that room is received
- [x] Show a notification on the message when a message is received

## Acceptance criteria
- [ ] When a user sends me a message and I am using the app, the message shows up in the room's thread in real-time
- [ ] When I am sent a message, I receive a notification
- [ ] When on another room and a message is received, navigating back to that room shows the received message
