### ISSUE TITLE
Channel-User interaction

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#13]
## Description
_As a user, I need to be able to view and leave channels so that I am involved in the conversations that matter to me._

## Tasks
- [ ] Channels I am a part of are shown in my sidebar
- [ ] UI option on channel page to leave the channel
- [ ] If leave channel, channel not shown in sidebar

## Acceptance criteria
- [ ] Can join existing channel
- [ ] Can leave existing channel

**Comment by skitterm** [comment]
Closing in favor of #7.
