### ISSUE TITLE
User presence

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#19]
## Description
_As a user, I want to be able to see who of my contacts is currently using the application, so I know who I can reasonably expect a quick reply from._

## Tasks
- [x] Determine how often need to know presence
- [x] Determine how to show presence vs not
- [x] Use web socket or DB to communicate your own presence (web socket, no need to poll anything and it's near-instantaneous updating)
- [x] "" to determine others' presence
- [x] Determine presence of others when load the app
- [x] Handle duplicate user items

## Acceptance criteria
- [x] Active users are shown differently than inactive users
