### ISSUE TITLE
Select database

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#2]
## Description
Research database options for the messaging app. The largest decision is whether to use SQL or NoSQL, but other considerations are also important:

Considerations:
* Types of data to store
* Integration with Node.js/Express
* Nature of interactions (write-heavy, read-heavy, etc)
* Flexibility for changing schema

## Tasks
- [x] Determine read/write balance of use cases
- [x] Review pros/cons of SQL/NoSQL
- [x] Create ordered/weighted criteria list
- [x] Investigate 3 options
- [x] Score based on criteria list
- [ ] Basic POC with selected option

## Acceptance criteria
- [x] List of criteria, ordered/weighted
- [x] List of possible choices
- [x] Selection of database, with rationale
- [ ] Proof-of-concept with selected database

**Comment by skitterm** [comment]
Criteria (13 points total):
* Flexible message data format (semistructured) (4)
* Efficient message storage (most messages small) (3)
* Easily relate messages to sender, recipients (3)
* Ease-of-use (2)
* Search from text across messages (1)

**Comment by skitterm** [comment]
Choice: MongoDB

How I got there:
I looked at what data would be stored the most in the database, and what operations would occur most frequently.
Messages will be the dominant item in the database -- users send hundreds, if not thousands, of them per year. Because a message is semistructured data (has some metadata but the message content is flexible, could be very short or very long, could include text, emojis, media, etc), I ruled out databases that focused mainly on structured data (SQL databases).

I found 3 operations that would be most important for the typical user:
1) Retrieve new, unread messages where user is recipient
1) Retrieve all recent messages between members of a room
1) Retrieve all of the user's contacts

Almost all of these queries would normally involve joins. In some cases, though, we could tolerate duplicate data if the query were quicker and simpler. This would be easy with a flexible schema, as we could easily store unread messages or users in a room via an array, instead of having to create a lookup table with multiple foreign keys.

I ruled out **key-value stores** because we'd need to query messages by their value (for the above queries, or for keyword searching).

I narrowed down to **document stores** (MongoDB) and **wide-column stores** (Cassandra). I went with **document stores** since it is easier to change schemas down the road (messages will need that flexibility), for simplicity of development (column-families and cql had a sharper learning curve), and because a document wouldn't waste much space in the database (if a message has only 3 words, it would not take up unnecessary space needed for a message with 1,000 words).

How document stores hold up to the criteria:
* Flexible message data format (semistructured) (4 total) -- Document stores are ideal for unstructured data (4)
* Efficient message storage (most messages small -- 3 total) -- Documents have no set of required columns, thus little space is wasted (3)
* Easily relate messages to sender, recipients (3) -- More of a data modeling challenge, but shouldn't be an issue (2)
* Ease-of-use (2) -- MongoDB is widely-used and documentation looks decent (1.5)
* Search from text across messages (1) -- More of a search thing than a database thing, but storing in a document shouldn't impede searching too badly (1)
