### ISSUE TITLE
Create data design

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#22]
## Description
Create a data model for the messaging application. This model will be implementation-agnostic, and should apply across various database types.

## Tasks
- [x] Review the ER model
- [x] Create an Entity Relationship diagram of the data needed for the messaging application
- [x] Run a few use-cases through the data

## Acceptance criteria
- [x] ER diagram includes all major entities and relationships
- [x] Data model holds up to basic changes

**Comment by skitterm** [comment]
![ERDiagram](https://user-images.githubusercontent.com/5875149/76136848-eb20c200-5fea-11ea-915d-88e4f9840480.png)
