### ISSUE TITLE
Set up UI framework

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#23]
## Description
Set up a UI framework for the front-end of the application. This includes both the module loading solution and how the UI will move from the data to the DOM.

## Tasks
- [x] Determine if SSR is necessary (it's not, no need for SEO and entire app is auth-protected)
- [x] Decide between single-page or multi-page application (SPA; SEO not needed, easier to go offline, app is mostly one page anyway)
- [x] Select UI framework
- [ ] <s>Select test framework (if desired)</s>
- [x] Select module loader
- [x] Decide where client, server-side code will live (separate repos, monorepo, etc) (same repo for simplicity, separated by `client/server` folders)

## Acceptance criteria
- [x] Framework chosen
- [x] Language support added
- [x] Module loader (if needed) added
- [x] Brief description of how this will interface with backend
