### ISSUE TITLE
Set up Design System

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#24]
## Description
As a developer, I need a design system so that I can create UI from a predetermined palette. 
As a user, I want the app to have a clean, uniform look.

## Tasks
- [x] Determine set of 5-8 colors
- [x] Find font families and open-source options
- [x] Find free, open-source icon set
