### ISSUE TITLE
Learn MongoDB

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#25]
## Description
Having chosen MongoDB for the database, I need to learn how it works at a basic level before diving in.

## Tasks
- [x] Learn basics of Mongo's strengths
- [x] View examples of connecting via a driver
- [x] Learn how to do basic CRUD operations
