### ISSUE TITLE
Rich text messaging

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#27]
## Description
_As a user, I want to be able to send rich text to others, so my messages can be more expressive and effective._

## Tasks
- [ ] Decide on criteria
- [ ] Research 3 rich text editors
- [ ] Select editor
- [ ] Facilitate the following things in this editor

## Acceptance criteria
- [ ] Bold/italic/quote/strikethrough can be entered
- [ ] Emoji can be entered
- [ ] (optional) Bulleted, numbered lists can be used
- [ ] (optional) Images can be uploaded
