### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#3]
## Description
Design a database schema that will fulfill the needs of the message app. Schema format will vary depending on the type of database chosen (#2).

## Tasks
- [x] Learn how data is stored in MongoDB
- [x] Model out data after this pattern
- [x] Put model through most important use-cases

## Acceptance criteria
- [x] Written documentation of the schema for each stored type
- [x] Connect to MongoDB instance
- [x] Seed with dummy data that follows the schema
- [x] Carry out main operations, make sure they work as intended
