### ISSUE TITLE
Multi-person messaging

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#33]
## Description
_As a user, I need to be able to communicate with multiple people at the same time, instead of just one-on-one._

## Tasks

- [ ] Ability to add multiple people to a new room or an existing room
- [ ] When a message is sent, all these people are notified
- [ ] Room with multiple people shows all participants' names

## Acceptance criteria
- [ ] Sending a message can send to multiple members
