### ISSUE TITLE
Design server API

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#4]
## Description
Design the structure and main e ndpoints for the server-side API for the message app. Most likely this will be a RESTful API, if its constraints match the needs of the API.

## Tasks
- [x] Quickly review REST
- [x] Learn how REST is implemented in Express
- [x] Learn how to handle dynamic routes
- [x] Learn how to handle URL parameters

## Acceptance criteria
- [x] Simple use cases and diagram depicting how using the API will fulfill CRUD operations on the database
- [x] Description of how API is RESTful
- [x] List of endpoints

**Comment by skitterm** [comment]
![another](https://user-images.githubusercontent.com/5875149/78855975-3b1fe980-79da-11ea-9287-46ed82666d5b.jpg)

**Comment by skitterm** [comment]
Use cases:

* **Get all messages from a room:** GET `/rooms/:id/:messages`
* **Get all rooms a user belongs to:** GET `/users/:id/:rooms`
* **Send a message:** PUT `/messages`
