### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#6]
## Description
_As a user, I want to input my name, profile, and time zone so that those I message can easily identify me._

Create a page where a user can upload their photo, add their name, and select their time zone.

## Tasks
- [x] <s>Use styled-jsx</s> Blocked trying to get it working with CRA and typescript; using `styled-components` instead
- [x] Find, use grid system lib
- [x] Decide if should use modal or page (page, better linkability)
- [x] Navigate between messages, profile page/modal
- [x] Display all pages with same width, header, grid system
- [x] Create primitive `<input>`
- [x] Display user's name
- [x] Separate out routing, database interaction
- [x] Persist name
- [x] Create primitive `<button>`
- [x] Create time zone picker (dropdown)
- [x] Persist time zone
- [ ] <s>Display user's thumbnail</s>
- [ ] <s>Quickly select profile image tool (Gravatar?)</s>
- [ ] <s>Update, persist user's thumbnail</s>
- [ ] Handle errors with proper HTTP status codes
- [x] (if time) Spruce up UI
- [ ] <s>(if time) Quickly mitigate XSS (client and server-side)</s>

## Acceptance criteria
- [ ] Current profile properties are displayed on a page/modal
- [ ] Can upload photo
- [ ] Can add name
- [ ] Can select time zone
- [ ] Can update these fields after saving
