### ISSUE TITLE
Display user's contacts

### ISSUE THREAD

**Issue by skitterm** [skitterm/message-app#8]
## Description
_As a user, I need to at-a-glance view all of the channels and members to/from whom I've sent or received messages._

## Tasks
- [x] Display list of contacts, by name, that user has exchanged messages with
- [x] When click on a contact, retrieve the messages from them
- [ ] <s>(maybe) preload messages from contacts</s>

## Acceptance criteria
- [x] Members user has messaged with are listed
- [x] When clicking on a contact, message history with that contact is shown
